### ISSUE TITLE
Proposal update "edvs" route name

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/edv-spec#36]
we currently don't use "docs", but we do use "edvs"....

I would prefer HTTP routes that looked like:

```
/vaults/:vauld_id/documents/:document_id
```

or routes that looked like:

```
/edvs/:vauld_id/docs/:document_id
```

**Comment by msporny** [comment]
We depend on the structure to make the ZCAP implementation easier (structured zcaps via pathing). So, -1 to removing the current structure.

For renaming "vaults" to "edvs" -- vaults are too generic, there are many types of vaults, so using that might be problematic. 

I don't think we need to be consistent in "long names" vs. "abbreviations" -- what is it buying us and why is what we have already causing issues?

**Comment by dlongley** [comment]
Nesting is important as there's a single controller for the entire EDV and having the EDV identified in the URL can help simplify implementations. It is also important to enable zcap path-based attenuation which is also easier to implement and understand than many alternatives. Existing implementations rely on this already.

As for the names, we won't necessarily have an obvious abbreviation for other things (`query`, `history`, whatever else may get added). We chose `/edvs` as the root because it is more likely to be a unique name and it matches our spec directly. That may be the only place we end up abbreviating and that may be the "rule" for how we're being consistent.

**Comment by dmitrizagidulin** [comment]
Discussed on the Sep 2, 2021 call.

Proposal: Keep the routes as they currently are and close the issue, due to reasons mentioned in the discussion.
